### ISSUE TITLE
hacs 中下载不下来

### ISSUE THREAD

**Issue by bqgx** [NiaoBlush/impc_energy#1]
![image](https://github.com/NiaoBlush/impc_energy/assets/17638999/4ba239e2-e079-4074-8f48-29a1572605e4)
我通过这个下载不下来你所编写的集成

**Comment by NiaoBlush** [comment]
> ![image](https://user-images.githubusercontent.com/17638999/265942917-4ba239e2-e079-4074-8f48-29a1572605e4.png) 我通过这个下载不下来你所编写的集成

日志中显示 ```No assets found for release 'tags/0.1.0'```
但是这个release下是有东西的
我也是第一次写这个, 现在还在寻找解决办法

**Comment by NiaoBlush** [comment]
@bqgx 我在release中加了个zip包, 现在我在测试环境已经可以正常下载了
